### ISSUE TITLE
공지사항 작성 상단 고정 에러 발생

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-front#163]
상단고정으로 체크를 하고 작성해도 N으로 들어가고 체크를 안하고 작성해도 N으로 들어갑니다.

**Comment by Baekhyunjung** [comment]
스위치 공통화하면서 바뀐것 같아요. 일반 스위치로 하면 잘 됩니다. 고쳐볼게요,,,,
