### ISSUE TITLE
공지사항 수정 코드 이상

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-front#164]
const updateNotice = async () => {
        try {
            await DefaultAxios.put(`/api/notice/${currentNoticeSeq}`, {
                title: editNotice.title,
                content: editNotice.content,
                adminSeq: localStorage.getItem("adminSeq"), // 현재 관리자의 Seq
                state: selectedNotice.state
            });
            Swal.fire("성공", "공지사항이 수정되었습니다.", "success");
            handleUpdateCloseModal();
            getNotice(); // 목록 갱신
        } catch (e) {
            console.error("공지사항 수정 실패:", e);
            Swal.fire("오류", "공지사항 수정에 실패했습니다.", "error");
        }
    };
    이 코드에서 local에서는 adminSeq를 저장하고 있는게 아니라 암호화된 토큰을 가지고 있는건데 이걸 어떻게 빼내는 건지 내용이 없음

**Comment by changmeen** [comment]
추가적으로 확인해보니 에디터에서 타이틀과 컨텐트의 내용을 불러오지 못하고 있는 문제가 있는데 이건 에디터를 바꾸게 되면 다시 달라지는 문제라 임시로 강제 타이틀과 컨텐트를 보내도록 해놨습니다.
또한 state역시 수정 모달창에서 선택할 수 있는 부분이 없어서 기존의 state를 보내도록 해놨습니다.

**Comment by Baekhyunjung** [comment]
adminSeq 부분은 api를 수정해야 할거 같습니다. 에디터에 불러와서 title, content, state 업데이트는 할 수 있게 했습니다. api 수정되면 관련 부분 고쳐서 같이 올릴게요.
