### ISSUE TITLE
이메일/비밀번호 찾기 이슈

### ISSUE THREAD

**Issue by eastlighting1** [KEA-DoKebi/dalkom-front#224]
연결이 이상한 데로 갑니다

**Comment by eastlighting1** [comment]
https://github.com/KEA-DoKebi/dalkom-front/assets/31691750/1bd51005-3902-447f-9976-adb5e9e9f201

**Comment by juhye87** [comment]
아이디/비밀번호 찾기 원래 없습니다

**Comment by sungjun-singer** [comment]
연결 없애고 Swal 띄우는 걸로 수정했습니다.
