### ISSUE TITLE
마일리지 이슈

### ISSUE THREAD

**Issue by eastlighting1** [KEA-DoKebi/dalkom-front#225]
초기에 User 테이블에 있는 마일리지가 반영되지 않았다가(0원) 마일리지 신청 이후 반영이 되기 시작함.

**Comment by sungjun-singer** [comment]
로그인 후 메인페이지로 이동했을 때 마일리지가 0원으로 뜨나요?

**Comment by sungjun-singer** [comment]
로컬에서도 같은 문제가 발생하여 해결하고 커밋하겠습니다
