### ISSUE TITLE
특정 카테고리 업데이트 안됨

### ISSUE THREAD

**Issue by eastlighting1** [KEA-DoKebi/dalkom-front#226]
안에 내용이 없는 건지는 몰라도 내용 업데이트가 안됩니다

**Comment by eastlighting1** [comment]
https://github.com/KEA-DoKebi/dalkom-front/assets/31691750/2505f899-d1fc-42db-a3f7-568e1936cd3d

**Comment by sungjun-singer** [comment]
나중에 데이터가 들어가면 화면 업데이트 될겁니다. 
지금은 요청시 404에러 떠서 화면에 업데이트가 안되는건데 
404 뜰 때 상품이 없는 페이지 띄우도록 하겠습니다

**Comment by sungjun-singer** [comment]
상품 없을시 상품 준비중이라는 페이지 띄우게 수정했습니다.
