### ISSUE TITLE
결제 성공이라고 뜨지만 결제 실패라고 밑에 뜸

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-front#233]
![에러](https://github.com/KEA-DoKebi/dalkom-front/assets/73987361/dc7bb884-8fa0-47be-b827-8464c37e0159)
장바구니에 여러 개를 담고 주문들 눌렀더니 저런식으로 화면이 뜸

**Comment by sungjun-singer** [comment]
해결했습니다!
