### ISSUE TITLE
결제에 성공했고 주문 목록에서 주문 상세를 누르면 에러가 발생함

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-front#234]
![image](https://github.com/KEA-DoKebi/dalkom-front/assets/73987361/3822f411-d41d-44f7-bf7c-81147f629444)

**Comment by allrightDJ0108** [comment]
주문 상세 화면 이동 시 에러 페이지로 반환되는 문제 해결했습니다.

원인 : window.location.href로 페이지를 이동하도록 설정되어 있었고, 이 방식은 페이지 새로고침 방식으로 이동되기 때문에 오류페이지로 반환됨.

해결 : window.location.href가 아닌 navigate를 통해 이동하도록 수정
@sungjun-singer
