### ISSUE TITLE
주문 문의 작성을 하려는데 에러 발생

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-front#235]
![image](https://github.com/KEA-DoKebi/dalkom-front/assets/73987361/5b5abd04-e0cf-44c5-9c5f-c8e5b88e6fec)

**Comment by changmeen** [comment]
사진을 지우고 글만 작성하니 다시 정상 작동함
글 사진 글 순으로 내용을 넣으면 에러가 발생하는지 확인 필요

**Comment by sungjun-singer** [comment]
글 사진 글 순으로 내용 넣어본 결과 에러 발생하지 않았는데 아직도 에러가 발생하나요?
